export default {
    platforms: [
        {posX:4, BlockW:1, BlockH:3},
        {posX:7, BlockW:1, BlockH:8},
        {posX:9, BlockW:2, BlockH:10},
        {posX:12, BlockW:6, BlockH:2},
        {posX:15, BlockW:3, BlockH:1, posY:4},
        {posX:20, BlockW:1, BlockH:9},
        {posX:22, BlockW:2, BlockH:14},
        {posX:25, BlockW:5, BlockH:3},
        {posX:31, BlockW:3, BlockH:6, posY:6},
        {posX:36, BlockW:1, BlockH:15},
        {posX:38, BlockW:1, BlockH:16},
        {posX:40, BlockW:1, BlockH:17},
        {posX:42, BlockW:1, BlockH:18},
        {posX:44, BlockW:8, BlockH:3},
        {posX:53, BlockW:2, BlockH:12, posY:12},
        {posX:57, BlockW:2, BlockH:14, posY:14},
        {posX:61, BlockW:2, BlockH:16, posY:16},
        {posX:66, BlockW:1, BlockH:20},
        {posX:70, BlockW:4, BlockH:18},
        {posX:76, BlockW:2, BlockH:8, posY:8},
        {posX:79, BlockW:2, BlockH:10, posY:10},
        {posX:82, BlockW:2, BlockH:12, posY:12},
        {posX:85, BlockW:1, BlockH:14, posY:14},
        {posX:82, BlockW:3, BlockH:2}
    ],

    collectiblesForm: [
        {posX:16, posY:5},
        {posX:23, posY: 15},
        {posX:32, posY:7},
        {posX:37, posY:17},
        {posX:39, posY:18},
        {posX:41, posY:19}
    ],

    hazards: [
        {type:"spike", posX:5, posY:1},
        {type:"spike", posX:12, posY:3},
        {type:"spike", posX:13, posY:3},
        {type:"spike", posX:15, posY:3},
        {type:"spike", posX:17, posY:1},
        {type:"spike", posX:25, posY:4},
        {type:"spike", posX:27, posY:4},
        {type:"spike", posX:29, posY:1},
        {type:"spike", posX:31, posY:1},
        {type:"spike", posX:33, posY:1},
        {type:"spike", posX:52, posY:1},
        {type:"spike", posX:54, posY:1},
        {type:"spike", posX:56, posY:1},
        {type:"spike", posX:58, posY:1},
        {type:"spike", posX:60, posY:1},
        {type:"spike", posX:62, posY:1},
        {type:"spike", posX:64, posY:1},
        {type:"spike", posX:66, posY:1},
        {type:"spike", posX:59, posY:15},
        {type:"spike", posX:61, posY:15},
        {type:"spike", posX:76, posY:1},
        {type:"spike", posX:78, posY:1},
        {type:"spike", posX:80, posY:1},
        {type:"spike", posX:82, posY:3},
        {type:"spike", posX:84, posY:1},
        {type:"spike", posX:86, posY:1},
        {type:"spike", posX:88, posY:1},
        {type:"spike", posX:90, posY:1},
        {type:"spike", posX:92, posY:1},


        {type:"grass", posX:44, posY:4},
        {type:"grass", posX:46, posY:4},
        {type:"grass", posX:48, posY:4},
        {type:"grass", posX:50, posY:4},
        {type:"grass", posX:70, posY:19},
        {type:"grass", posX:72, posY:19},

        {type:"weed", posX:68, posY:1},
        {type:"weed", posX:69, posY:1},
        {type:"weed", posX:70, posY:1},
        {type:"weed", posX:74, posY:1},
        {type:"weed", posX:75, posY:1}
    ],

    texts: []
}
